// Code generated by protoc-gen-go. DO NOT EDIT.
// source: welcomepb/welcome.proto

package welcomepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Person struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_46790a53682c3a6a, []int{0}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Person) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type WelcomeEveryoneRequest struct {
	Person               *Person  `protobuf:"bytes,1,opt,name=person,proto3" json:"person,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WelcomeEveryoneRequest) Reset()         { *m = WelcomeEveryoneRequest{} }
func (m *WelcomeEveryoneRequest) String() string { return proto.CompactTextString(m) }
func (*WelcomeEveryoneRequest) ProtoMessage()    {}
func (*WelcomeEveryoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46790a53682c3a6a, []int{1}
}

func (m *WelcomeEveryoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeEveryoneRequest.Unmarshal(m, b)
}
func (m *WelcomeEveryoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeEveryoneRequest.Marshal(b, m, deterministic)
}
func (m *WelcomeEveryoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeEveryoneRequest.Merge(m, src)
}
func (m *WelcomeEveryoneRequest) XXX_Size() int {
	return xxx_messageInfo_WelcomeEveryoneRequest.Size(m)
}
func (m *WelcomeEveryoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeEveryoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeEveryoneRequest proto.InternalMessageInfo

func (m *WelcomeEveryoneRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

type WelcomeEveryoneResponse struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WelcomeEveryoneResponse) Reset()         { *m = WelcomeEveryoneResponse{} }
func (m *WelcomeEveryoneResponse) String() string { return proto.CompactTextString(m) }
func (*WelcomeEveryoneResponse) ProtoMessage()    {}
func (*WelcomeEveryoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46790a53682c3a6a, []int{2}
}

func (m *WelcomeEveryoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WelcomeEveryoneResponse.Unmarshal(m, b)
}
func (m *WelcomeEveryoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WelcomeEveryoneResponse.Marshal(b, m, deterministic)
}
func (m *WelcomeEveryoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WelcomeEveryoneResponse.Merge(m, src)
}
func (m *WelcomeEveryoneResponse) XXX_Size() int {
	return xxx_messageInfo_WelcomeEveryoneResponse.Size(m)
}
func (m *WelcomeEveryoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WelcomeEveryoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WelcomeEveryoneResponse proto.InternalMessageInfo

func (m *WelcomeEveryoneResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Person)(nil), "welcome.Person")
	proto.RegisterType((*WelcomeEveryoneRequest)(nil), "welcome.WelcomeEveryoneRequest")
	proto.RegisterType((*WelcomeEveryoneResponse)(nil), "welcome.WelcomeEveryoneResponse")
}

func init() { proto.RegisterFile("welcomepb/welcome.proto", fileDescriptor_46790a53682c3a6a) }

var fileDescriptor_46790a53682c3a6a = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x4f, 0xcd, 0x49,
	0xce, 0xcf, 0x4d, 0x2d, 0x48, 0xd2, 0x87, 0xb2, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8,
	0xa1, 0x5c, 0x25, 0x17, 0x2e, 0xb6, 0x80, 0xd4, 0xa2, 0xe2, 0xfc, 0x3c, 0x21, 0x59, 0x2e, 0xae,
	0xb4, 0xcc, 0xa2, 0xe2, 0x92, 0xf8, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce,
	0x20, 0x4e, 0xb0, 0x88, 0x5f, 0x62, 0x6e, 0xaa, 0x90, 0x34, 0x17, 0x67, 0x4e, 0x22, 0x4c, 0x96,
	0x09, 0x2c, 0xcb, 0x01, 0x12, 0x00, 0x49, 0x2a, 0x39, 0x72, 0x89, 0x85, 0x43, 0x0c, 0x74, 0x2d,
	0x4b, 0x2d, 0xaa, 0xcc, 0xcf, 0x4b, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe7,
	0x62, 0x2b, 0x00, 0x9b, 0x0f, 0x36, 0x91, 0xdb, 0x88, 0x5f, 0x0f, 0xe6, 0x10, 0x88, 0xb5, 0x41,
	0x50, 0x69, 0x25, 0x43, 0x2e, 0x71, 0x0c, 0x23, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xc4,
	0xb8, 0xd8, 0x8a, 0x52, 0x8b, 0x4b, 0x73, 0x4a, 0xa0, 0xae, 0x82, 0xf2, 0x8c, 0x72, 0xb8, 0xf8,
	0xa0, 0x5a, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0xa2, 0xb8, 0xf8, 0xd1, 0x0c, 0x11,
	0x92, 0x87, 0x5b, 0x88, 0xdd, 0x85, 0x52, 0x0a, 0xb8, 0x15, 0x40, 0xec, 0x57, 0x62, 0xd0, 0x60,
	0x34, 0x60, 0x74, 0xe2, 0x8e, 0xe2, 0x84, 0x87, 0x66, 0x12, 0x1b, 0x38, 0x18, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xec, 0x6e, 0x1f, 0x85, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WelcomeServiceClient is the client API for WelcomeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WelcomeServiceClient interface {
	WelcomeEveryone(ctx context.Context, opts ...grpc.CallOption) (WelcomeService_WelcomeEveryoneClient, error)
}

type welcomeServiceClient struct {
	cc *grpc.ClientConn
}

func NewWelcomeServiceClient(cc *grpc.ClientConn) WelcomeServiceClient {
	return &welcomeServiceClient{cc}
}

func (c *welcomeServiceClient) WelcomeEveryone(ctx context.Context, opts ...grpc.CallOption) (WelcomeService_WelcomeEveryoneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_WelcomeService_serviceDesc.Streams[0], "/welcome.WelcomeService/WelcomeEveryone", opts...)
	if err != nil {
		return nil, err
	}
	x := &welcomeServiceWelcomeEveryoneClient{stream}
	return x, nil
}

type WelcomeService_WelcomeEveryoneClient interface {
	Send(*WelcomeEveryoneRequest) error
	Recv() (*WelcomeEveryoneResponse, error)
	grpc.ClientStream
}

type welcomeServiceWelcomeEveryoneClient struct {
	grpc.ClientStream
}

func (x *welcomeServiceWelcomeEveryoneClient) Send(m *WelcomeEveryoneRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *welcomeServiceWelcomeEveryoneClient) Recv() (*WelcomeEveryoneResponse, error) {
	m := new(WelcomeEveryoneResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WelcomeServiceServer is the server API for WelcomeService service.
type WelcomeServiceServer interface {
	WelcomeEveryone(WelcomeService_WelcomeEveryoneServer) error
}

// UnimplementedWelcomeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedWelcomeServiceServer struct {
}

func (*UnimplementedWelcomeServiceServer) WelcomeEveryone(srv WelcomeService_WelcomeEveryoneServer) error {
	return status.Errorf(codes.Unimplemented, "method WelcomeEveryone not implemented")
}

func RegisterWelcomeServiceServer(s *grpc.Server, srv WelcomeServiceServer) {
	s.RegisterService(&_WelcomeService_serviceDesc, srv)
}

func _WelcomeService_WelcomeEveryone_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WelcomeServiceServer).WelcomeEveryone(&welcomeServiceWelcomeEveryoneServer{stream})
}

type WelcomeService_WelcomeEveryoneServer interface {
	Send(*WelcomeEveryoneResponse) error
	Recv() (*WelcomeEveryoneRequest, error)
	grpc.ServerStream
}

type welcomeServiceWelcomeEveryoneServer struct {
	grpc.ServerStream
}

func (x *welcomeServiceWelcomeEveryoneServer) Send(m *WelcomeEveryoneResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *welcomeServiceWelcomeEveryoneServer) Recv() (*WelcomeEveryoneRequest, error) {
	m := new(WelcomeEveryoneRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _WelcomeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "welcome.WelcomeService",
	HandlerType: (*WelcomeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WelcomeEveryone",
			Handler:       _WelcomeService_WelcomeEveryone_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "welcomepb/welcome.proto",
}
